# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3a783acd5035c155c20928a73039ca61"
name = "test-adminapi-2"
handle = "test-adminapi-2"
application_url = "https://nh-dad-assess-michigan.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "fitunions-test1.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://nh-dad-assess-michigan.trycloudflare.com/auth/callback",
  "https://nh-dad-assess-michigan.trycloudflare.com/auth/shopify/callback",
  "https://nh-dad-assess-michigan.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
